name: CI/CD with Docker

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies and run tests
      run: |
        npm install
        npm test

  docker-build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t projekt1:${{ github.sha }} .

    - name: Test Docker image
      run: |
        docker run -d -p 3000:3000 --name test-container projekt1:${{ github.sha }}
        sleep 10
        curl -f http://localhost:3000 || exit 1
        docker stop test-container

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to remote server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        script: |
          docker pull projekt1:${{ github.sha }} || true
          docker stop projekt1 || true
          docker rm projekt1 || true
          docker run -d -p 3000:3000 --name projekt1 projekt1:${{ github.sha }}
